// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkoAZ8lXjRTUbzy7MOG3D-rIQd01IW6I',
    appId: '1:513558883819:web:963f711c7558ff92e7fdae',
    messagingSenderId: '513558883819',
    projectId: 'fcmflutter-c8d47',
    authDomain: 'fcmflutter-c8d47.firebaseapp.com',
    storageBucket: 'fcmflutter-c8d47.appspot.com',
    measurementId: 'G-HQPSWH8C08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XFsK4wgEDWU3FiRdbGi37Ywhq-v0IMk',
    appId: '1:513558883819:android:6c6138b182231c50e7fdae',
    messagingSenderId: '513558883819',
    projectId: 'fcmflutter-c8d47',
    storageBucket: 'fcmflutter-c8d47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYkLtb7a51Bsyspa6rjIHADxQAgCfEDA',
    appId: '1:513558883819:ios:8e23fa793743e8c9e7fdae',
    messagingSenderId: '513558883819',
    projectId: 'fcmflutter-c8d47',
    storageBucket: 'fcmflutter-c8d47.appspot.com',
    iosClientId: '513558883819-tgo926723sbr3d2ksiu6umc5hjue1s51.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXYkLtb7a51Bsyspa6rjIHADxQAgCfEDA',
    appId: '1:513558883819:ios:8e23fa793743e8c9e7fdae',
    messagingSenderId: '513558883819',
    projectId: 'fcmflutter-c8d47',
    storageBucket: 'fcmflutter-c8d47.appspot.com',
    iosClientId: '513558883819-tgo926723sbr3d2ksiu6umc5hjue1s51.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification',
  );
}
